services:
  gateway:
    build:
      context: .
      dockerfile: ORMConvertorAPI/Dockerfile
    ports:
      - "5072:5072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    depends_on:
      - translation-service
      - metadata-service
      - advisor-service

  translation-service:
    build:
      context: .
      dockerfile: TranslationService/Dockerfile
    ports:
      - "5082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  metadata-service:
    build:
      context: .
      dockerfile: MetadataService/Dockerfile
    ports:
      - "5083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  advisor-service:
    build:
      context: .
      dockerfile: AdvisorService/Dockerfile
    ports:
      - "5084:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql_db
    restart: unless-stopped

  mssql_db:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "1444:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Testingorms123
      - MSSQL_PID=Developer
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
